### ISSUE TITLE
Tools/science parser jar file doesn't work

### ISSUE THREAD

**Issue by HaritzPuerto** [LARC-CMU-SMU/rclc_2019_baseline#1]
Hi! I'm trying to use your code to download the publications and convert them into .txt files but I cannot use the science parser. I think it is a symbolic link because I found this 

`science-parse-cli-assembly-2.0.2-SNAPSHOT.jar -> ../../coleridge-rich-context-larc/project/tools/science-parse-cli-assembly-2.0.2-SNAPSHOT.jar`

Thanks for your work!!

**Comment by philipskokoh** [comment]
So sorry, I committed a symbolic link. It's fixed now.
Closed via af315409d97b38213d2da2fa87f85a671faa7e04
