### ISSUE TITLE
Error converting to txt 2b4497873374d080d359.pdf

### ISSUE THREAD

**Issue by HaritzPuerto** [LARC-CMU-SMU/rclc_2019_baseline#2]
Hi,

I discovered that 2b4497873374d080d359.pdf is not converted well into .txt. I only got an empty file. But the pdf is ok. Do you also have this problem, or is it only me?

Thank you

**Comment by philipskokoh** [comment]
Yes, I have the same problem. I am not able to process scanned pdf document. If you open this kind of pdf files, all contents are image.

Thanks to pointing out this issue. I think it would be good to open an issue about this and discuss this in [rclc](https://github.com/Coleridge-Initiative/rclc) repo with Paco.

**Comment by HaritzPuerto** [comment]
Yeah, I was suspecting that was the issue. This kind of documents require a totally different approach to obtain the txt file.

Sure, I will open an issue in rclc repo to discuss it with Paco. Thanks @philipskokoh
